name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test
        run: go test -mod vendor ./...
